version: "3.8"

services:
  main:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "FORGE"
      MEMORY: 4G
    volumes:
      - ./data:/data
      - ./mods:/mods:ro
      - /etc/timezone:/etc/timezone:ro
    tty: true
    stdin_open: true
    restart: always
    deploy:
      resources:
        limits:
          memory: 5G

  backup:
    image: itzg/mc-backup
    depends_on:
      - main
    volumes:
      - ./data:/data:ro
      - ./backups:/backups
      - /etc/timezone:/etc/timezone:ro
    network_mode: "service:main"
